### ISSUE TITLE
Schema Checklist

### ISSUE THREAD

**Issue by iProgYou** [chrisaugust29/myhelpapp#3]
# Database Schema
- [x] Contains correct datatypes
- [ ] Contains appropriate constraints/details
    - [x] primary key
    - [x] not null
    - [x] unique
    - [x] indexed
    - [ ] foreign key
- [ ] Contains bullet points after the table that state which foreign keys will reference to which table, or references to the associations which will be made
  - [ ] foreign key and table name are lowercased, snake_cased and `back_ticked`
- [ ] Correctly formatted
    - [x] schema is written in a table format
    - [ ] the table's name are lowercased, snake_cased and `back_ticked`
    - [ ] the table header column names are bolded
    - [ ] columns names are lowercased and snaked_cased and `back_ticked`
## Comments
- Formatting could use some work. Try mimicking the format of Bluebird wiki
- If there is a one-to-many relationship between users and businesses, then businesses should have a `user_id` foreign key

**Comment by iProgYou** [comment]
I spoke with Alex about how I would recommend handling `category`. If a business is going to have many categories, you will need another table (a joins table). Definitely talk with Alex and let me know if you have questions.

**Comment by iProgYou** [comment]
- First name and last name should be separate columns
- I don't think you need a location column
- You need a `business_category` table to join your categories and businesses
- Still no foreign key in business. Let me know if you have questions on this.

**Comment by chrisaugust29** [comment]
- Updated first and last name
- removed locations 
- added new joins table 
- and added creator id for business table

**Comment by iProgYou** [comment]
Looks Good!
